site_name: UI Services

extra_css:
  - stylesheets/extra.css
theme:   
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde